CREATE TABLE tb_usuario (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR (100) NOT NULL,
    senha VARCHAR (20),
    token VARCHAR(50) NULL,

);

ALTER TABLE tb_usuario
ADD COLUMN email varchar(100);

ALTER TABLE tb_usuario
ADD COLUMN status INT DEFAULT 1;

ALTER TABLE tb_usuario
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE tb_usuario
ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

